config/routes.rb
Rails.application.routes.draw do
  resources :quotes do
  end
      
    
      get 'quotes/sort_by_saying_length'
      get 'quotes/sort_by_said_by_length'
      get 'quotes/sort_by_year_length'

root 'quotes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
# app/models/message.rb
class Message < ApplicationRecord
    has_rich_text :content
  end
  

app/models/quote.rb
class Quote < ApplicationRecord
    has_rich_text :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
        @pages = Pages.order(params[:sort])
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [ :show, :edit, :update, :destroy ]

  # GET /quotes or /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1 or /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  def vote
  end

  # POST /quotes or /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully created." }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1 or /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully updated." }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1 or /quotes/1.json
  def destroy
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to quotes_url, notice: "Quote was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_params
      params.require(:quote).permit(:saying_length, :said_by_length, :year_length, :saying, :said_by, :votes, :year, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quoting</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quotes/_form.html.erb
<%= form_with(model: quote) do |form| %>
  <% if quote.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
        <% quote.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :saying_length, class: "form-label" %>
    <%= form.text_field :saying_length, class: "form-control" %>
  </div>

  <div>
    <%= form.label :said_by_length, class: "form-label" %>
    <%= form.text_field :said_by_length, class: "form-control" %>
  </div>

  <div>
    <%= form.label :votes, style: "display: block" %>
    <%= form.number_field :votes %>
  </div>

  <div>
    <%= form.label :year_length, class: "form-label" %>
    <%= form.number_field :year_length, class: "form-control" %>
  </div>

 <div class="field">
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/quotes/_quote.html.erb
<div id="<%= dom_id quote %>">
  <p>
    <strong>Saying:</strong>
    <%= quote.saying_length %>
  </p>

  <p>
    <strong>Said by:</strong>
    <%= quote.said_by_length %>
  </p>

  <p>
    <strong>Votes:</strong>
    <%= quote.votes %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= quote.year_length %>
  </p>

  <p>
    <strong>Notes:</strong>
    <%= quote.notes %>
  </p>

</div>

app/views/quotes/edit.html.erb
<h1>Editing quote</h1>

<%= render "form", quote: @quote %>

<br>

<div>
  <%= link_to "Back to quotes", quotes_path, class: "btn btn-secondary" %>
</div>

app/views/quotes/index.html.erb
<h1 class="d-flex justify-content-center">Quotes</h1>
<%= link_to new_quote_path, class: "btn btn-primary" do %>
 <i class="bi bi-plus" ></i> New Quote
 <%= link_to 'Sort Quote', quotes_sort_by_saying_length_path, class: "btn btn-primary" %>
  <%= link_to 'Sort Quote By', quotes_sort_by_said_by_length_path, class: "btn btn-primary" %>
   <%= link_to 'Sort By Year', quotes_sort_by_year_length_path, class: "btn btn-primary" %>
<% end %>

<table class="table">
<thead>
<tr>
<th>Quote</th>
<th>Quote by</th>
<th>Votes</th>
<th>Year</th>
<th>Facts</th>
<th></th>
<th></th>
<thead>
</tr>
  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.saying_length %></td>
        <td><%= quote.said_by_length %></td>
        <td><%= quote.votes %></td>
        <td><%= quote.year_length %></td>
        <td><%= quote.notes %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote), class: "btn btn-primary" %></td>
        <td><%= button_to 'Delete', quote, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/quotes/new.html.erb
<h1>New quote</h1>

<%= render "form", quote: @quote %>

<br>

<div>
  <%= link_to "Back to quotes", quotes_path, class: "btn btn-secondary"  %>
</div>

app/views/quotes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @quote %>

<div>
  <%= link_to "Edit this quote", edit_quote_path(@quote) %> |
  <%= link_to "Back to quotes", quotes_path %>
  
</div>